### ISSUE TITLE
PO details not updated after changing qty

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/receiving#119]
## Current behavior

When changing the qty value and receiving the PO, qty received not being updated and qty field does not reset.

## Expected behavior

PO details should be updated automatically without refreshing the page

## Steps to reproduce the issue

- Go to po details page
- Update the qty for an item and receive the po
- Go to the same po again from list page
- See that the po details (qty received and qty field) not being updated
- Refresh the page and verify that the po details being updated

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by adityasharma7** [comment]
This is done with https://github.com/hotwax/receiving/pull/124. Closing
