### ISSUE TITLE
Show shipments, returns, and POs that cannot be received.

### ISSUE THREAD

**Issue by dt2patel** [hotwax/receiving#131]
## What is the motivation for adding/enhancing this feature?

Users should be able to go back and view a shipment even after it has been received, canceled, or completed. This helps in reviewing or verifying data incase they need to be reconciled.

## What are the acceptance criteria?

On the list page, all results show show up regardless of status. On the detail page, users won't be able to edit these items with clear indications that this shipment has been completed etc.

## Additional information

![Return list](https://user-images.githubusercontent.com/60128132/191912462-a8cb525f-acbf-45e7-9f08-8198833917f9.png)

![Return detail received](https://user-images.githubusercontent.com/60128132/191912097-afc3a067-0c93-4d6e-bfcb-c554909e2b08.png)

**Comment by adityasharma7** [comment]
This is done with https://github.com/hotwax/receiving/pull/132/files. Closing
