### ISSUE TITLE
Enable auto-focus on actionable content for all the pages

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/receiving#133]
## What is the motivation for adding/enhancing this feature?

This feature will help the users to easily navigate through the app

## What are the acceptance criteria?

- [ ] The input fields and buttons should be in focus on tab key
- [ ] When searched for specific string, if some data found then the first item in the list should be in focus

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by k2maan** [comment]
Checked the use of `netxTick` with Ionic lifecycle hooks, not working.
