### ISSUE TITLE
Add current instance details to sidebar footer.

### ISSUE THREAD

**Issue by dt2patel** [hotwax/receiving#149]
## What is the motivation for adding/enhancing this feature?
Like the Job Manager app, the sidebar footer should show the current connected instance and product store.
<img width="852" alt="Screen Shot 2022-10-14 at 9 50 15 AM" src="https://user-images.githubusercontent.com/60128132/195761642-9a9c852b-baa8-4fc2-abd7-741da36bc298.png">

**Comment by yogesh-9999** [comment]
assign it to me

**Comment by dt2patel** [comment]
will implement later as part of common component
