### ISSUE TITLE
Show order and item status on POs

### ISSUE THREAD

**Issue by dt2patel** [hotwax/receiving#152]
## What is the motivation for adding/enhancing this feature?

Only Approved POs can be received. Right now we don't show the status of the PO which makes it hard to know that can and cannot be received.

There should be a badge on the end slot of the find screen with a badge that shows the status.

On the detail page, next to the internal order id badge, there should be an order level status badge.

For items, the receive all button should be replaced with a "completed" badge when the item status has changed to completed.

**Comment by ymaheshwari1** [comment]
Reopening as the `Receive All` button is not replaced with completed badge

**Comment by Dhiraj1405** [comment]
Will be taken care with issue #259
