### ISSUE TITLE
Create dedicated empty states

### ISSUE THREAD

**Issue by dt2patel** [hotwax/receiving#221]
## What is the motivation for adding/enhancing this feature?

All find screens should have dedicated empty states that show the user relevant information instead of a load more button when there is no more data to load.

When there are no more shipments to load, the current toast makes it feel like a bug. There should be no toast if there are no more shipments to load, instead it should switch to the empty state

**Comment by dt2patel** [comment]
@Nidbhagwat please provide mockups for empty states for all pages.

**Comment by Nidbhagwat** [comment]
> @Nidbhagwat please provide mockups for empty states for all pages.

Yes, sir.

**Comment by Nidbhagwat** [comment]
> @Nidbhagwat please provide mockups for empty states for all pages.

Here is the Figma file link for all find pages- empty state.

https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-(Community)-(Nidhi--2023)?node-id=24666%3A91461&t=h5lbDYh3fBgUCSWp-1

**Comment by ymaheshwari1** [comment]
I think we should also have empty state for history modal.

![image](https://user-images.githubusercontent.com/41404838/232681366-dd192e36-1534-4f63-b0bf-192033202a33.png)

**Comment by Nidbhagwat** [comment]
https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-(Community)-(Nidhi--2023)?node-id=24666%3A91461&t=zLhxYnTkwIL8ujRt-1

**Comment by Nidbhagwat** [comment]
Updated link for the empty state- Receiving app:

https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-(Community)-(Nidhi--2023)?type=design&node-id=13525%3A0&t=1oyYUKthuUG3AUKU-1
