### ISSUE TITLE
Implement product identifier using dxp-component.

### ISSUE THREAD

**Issue by sanskar345** [hotwax/receiving#246]
## What is the motivation for adding/enhancing this feature?

To use dxp-components to implement product Identifier.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
@ravilodhi There is a ticket per app. If its done or not going to be picked, I can close them all. Let me know your opinion

**Comment by ravilodhi** [comment]
@Dhiraj1405 
We can keep these tickets as of now. We can plan these soon.

**Comment by ravilodhi** [comment]
@Adameddy26 We can close this ticket if product identifier is working fine.

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v2.28.1. Hence, closing this ticket.
