### ISSUE TITLE
Add Pointer on Hover for Completed Items Icon

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/receiving#271]
## Current behavior
Currently, on the Purchase Order Detail page, the completed items icons lack visual feedback to indicate their clickability. This can cause confusion among users, leading to a less intuitive user experience.

## Expected behavior
To enhance user experience and make the interface more user-friendly, we should add a pointer cursor on hover for the completed items icons. This simple yet effective visual cue will clearly indicate to users that these icons are clickable actions.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by MohitNamdev22** [comment]
Hey @Dhiraj1405 Can you assign it to me? I would definitely love to work on this issue under Hacktoberfest event 2023 @Hotwax

**Comment by k2maan** [comment]
Sure @MohitNamdev22, go ahead

**Comment by ravilodhi** [comment]
The current solution needs to improve as this is the wrong approach to fixing this. Instead, we should put icon in a button with slot icon only.
