### ISSUE TITLE
 Add Empty States for "Add Items" Modal on Shipments and Purchase Orders Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/receiving#272]
## What is the motivation for adding/enhancing this feature?
Currently, when users open the "Add Items" modal on the Shipments and Purchase Orders page, there is no clear indication of what to do or what items can be added. This lack of information can be confusing for users, especially when they are new to the system.

## What are the acceptance criteria?
To enhance user understanding and guide them effectively, we should implement an empty state for the "Add Items" modal. This empty state will provide a clear message or visual representation that there are no items to add, ensuring that users are aware of the context.

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
Find UI here: 
https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-(Community)-(Nidhi--2023)?type=design&node-id=25814%3A115756&mode=design&t=vlJFFIZBdh4ynJZS-1)[https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-(Community)-(Nidhi--2023)?type=design&node-id=25814%3A115756&mode=design&t=vlJFFIZBdh4ynJZS-1](https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-%28Community%29-%28Nidhi--2023%29?type=design&node-id=25814%3A115756&mode=design&t=vlJFFIZBdh4ynJZS-1

**Comment by Preetvani07** [comment]
hello @Dhiraj1405 sir, i want to contribute in this issue can you assign me this issue?

**Comment by k2maan** [comment]
Sure @Preetvani07 go ahead

**Comment by Dhiraj1405** [comment]
> hello @Dhiraj1405 sir, i want to contribute in this issue can you assign me this issue?

Sure, go ahead.

**Comment by Preetvani07** [comment]
sir i mistakely unassigned this issue can you please reassign me this issue
