### ISSUE TITLE
Change Label Text Case for Pending and Completed Items on Purchase Order Detail Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/receiving#273]
## Current behavior
The label text for Pending and Completed items on the Purchase Order detail page is displayed in all caps.

## Expected behavior
The label text for Pending and Completed items on the Purchase Order detail page should be displayed in title case.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by HitikaGhanani** [comment]
Hello @Dhiraj1405 Sir, I would like to contribute to this issue, can you please assign it to me?

**Comment by ymaheshwari1** [comment]
Sure go ahead @HitikaGhanani

**Comment by Preetvani07** [comment]
can you assign me this issue?

**Comment by Dhiraj1405** [comment]
> can you assign me this issue?

This issue is already assigned, please pick another issue.
