### ISSUE TITLE
Add the product on product scan even if it is not returned or a part of shipment/purchase order to reduce the manual efforts.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/receiving#324]
## What is the motivation for adding/enhancing this feature?
To make it easy for user to scan and directly receive a product which is not a part of PO, shipment or being returned to store.
When user scans any ASN and founds any unexpected product which is not a part of PO/return/shipment then instead of manually clicking on (+) button on details page and adding it to shipment/PO; user should be given an option to scan and add it directly.

## What are the acceptance criteria?
Product should exist in Shopify and Hotwax.

**Comment by dt2patel** [comment]
The toast message should give a button to open the add product modal. We don't want user to be able to add items to the shipment too easily to avoid user error.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.26.0. Hence, closing it.
https://jam.dev/c/c649a508-3238-46d0-960f-42bc9a40d57c
