### ISSUE TITLE
Adding `Force Scan` card on Settings page

### ISSUE THREAD

**Issue by sanjanashrivastava** [hotwax/receiving#325]
## What is the motivation for adding/enhancing this feature?
We need to add a `Force Scan` card on the Settings page of the Receiving app to ensure increment of received quantity occurs only by scanning product barcodes.

Adding screenshots of the expected version along with the link to the preview of page in the HC Ionic Figma file.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information

<img width="279" alt="Force Scan" src="https://github.com/hotwax/receiving/assets/155512107/63ce8997-80bf-4eab-bf16-c217c43265c5">

https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=29950%3A102273&mode=design&t=pPAR3o1kyRjaLQCF-1

**Comment by dt2patel** [comment]
At some point our clients will follow up on what happened to this feature, we will need to have it implemented for that.

**Comment by Adameddy26** [comment]
Verified the changes and are working fine in release v2.27.0. Hence,closing it.
