### ISSUE TITLE
Add Arrival date and Internal id on Shipment Details page 

### ISSUE THREAD

**Issue by sanjanashrivastava** [hotwax/receiving#327]
Add `Arrival date` (if arrival date is available on the shipment) and `Internal id` for the shipment in chips on top right in front of Shipment details on the Shipment Details page in the Receiving app. 

Attaching screenshots and link to HC Ionic Figma file for clarity. 

__Current:__
<img width="1103" alt="Shipment details current" src="https://github.com/hotwax/receiving/assets/155512107/25e50015-d37e-4035-9834-0555b714de6e">

__Expected:__
<img width="1103" alt="Shipment details expected" src="https://github.com/hotwax/receiving/assets/155512107/2ba1cc41-fa81-4b26-bddc-a1b5124692e6">

https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=14699%3A34510&mode=design&t=fWAmimYR20yTJdsw-1

**Comment by dt2patel** [comment]
Not a priority, can remove
