### ISSUE TITLE
Updations in Shipments status on Shipments page in Receiving app

### ISSUE THREAD

**Issue by sanjanashrivastava** [hotwax/receiving#328]
On Shipments page currently the status of shipment is not inside a badge, it needs to be displayed in a badge for emphasis. Also the badges need to be color coded based on the status of the shipment. Attaching screenshots of the current and expected version below. 

__Current:__
<img width="1012" alt="Current" src="https://github.com/hotwax/receiving/assets/155512107/c969a845-c6fe-49e8-99ce-0cb31c2dee32">

__Expected:__
<img width="1012" alt="Expected" src="https://github.com/hotwax/receiving/assets/155512107/058ad4b1-a95b-4a96-81ea-5780f5fa485d">

 https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=23280%3A80705&mode=design&t=fWAmimYR20yTJdsw-1

**Comment by Adameddy26** [comment]
We are looking to add a badge for the type of the shipment rather than the status. All shipments here are in "Shipped" status.

**Comment by Dhiraj1405** [comment]
@Adameddy26 Should we close this one as the approach is completely changed

**Comment by Dhiraj1405** [comment]
We are closing this ticket as not required.
