### ISSUE TITLE
Logging out loader is getting displayed when logging-in into the app

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/receiving#337]
## Current behavior

When login into the app, loader with `logging out` message is displayed after `logging-in` loader

## Expected behavior

Only a loader saying `logging-in` needs to be displayed in login flow

## Steps to reproduce the issue

- Login into the app
- Verify that multiple loaders are displayed and one is with the message `logging out`

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in v2.24.0.
https://jam.dev/c/de1b20f3-5530-4e54-beeb-20bb37c8ac77
