### ISSUE TITLE
Partial Shipment/PO Product Receipt Allowed with Decimal Quantity Inputs

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/receiving#338]
## Current behavior
During the receipt process for shipments or purchase order (PO) products, users are able to input decimal values in the quantity field, allowing for partial receipt of products. 

## Expected behavior
The system should validate quantity inputs during the receipt process and restrict users from entering decimal values, ensuring that only whole numbers are accepted for product quantities. Users should be prompted to input whole numbers or complete quantities as specified in the order.

## Description
Users are able to receive shipments or purchase order (PO) products partially by entering decimal values in the quantity field during the receipt process. For instance, users may input fractional quantities such as 0.5 or 0.75, resulting in partial receipt of products instead of the complete quantities specified in the order. This issue undermines the accuracy and integrity of order fulfillment, potentially leading to discrepancies in inventory levels, customer dissatisfaction, and operational inefficiencies.

## Steps to reproduce the issue
Navigate to the shipment or PO receiving interface.
Select a shipment or PO to receive.
Enter a decimal value (e.g., 0.5, 0.75) in the quantity field instead of a whole number.
Confirm the receipt of the partial quantity.
Observe that the system accepts the partial receipt without alerting the user to the incomplete order fulfillment.

## Environment details
- App version: v2.23.1
- Environment: UAT

## Additional information
https://jam.dev/c/e14c1de5-ed59-4aae-b9cd-507a07258637

**Comment by Dhiraj1405** [comment]
Not required. Hence, closing.
