### ISSUE TITLE
PO Product Item Incorrectly Displayed as Pending Despite Full Receipt

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/receiving#342]
## Current behavior
When a user receives all of the ordered quantity for a purchase order (PO) product item, the item remains displayed in a pending state in the user interface (UI), despite moving it to completed category.

## Expected behavior
Upon receiving all of the ordered quantity for a PO product item, the item should transition to the completed state in the UI. Also 'Receive all' button should be disabled in this case.

## Steps to reproduce the issue
Receive a purchase order (PO) product item for the full ordered quantity.
Verify that the received quantity matches the ordered quantity.
Observe that the PO product item remains displayed in the pending state in the UI, despite all items being received.

## Environment details
- App version: v2.23.1- 
- Environment: UAT

## Additional information
https://jam.dev/c/2d08c1d1-b17b-4c95-a016-a5efda2d85fd

**Comment by dt2patel** [comment]
@Adameddy26 you have to explicitly close the items to move the items to the completed section. Please retest this ticket with "receive and close" function and share your findings

**Comment by Adameddy26** [comment]
@dt2patel Retested the ticket with "receive and close" function and found that item is still in pending state. On refreshing the URL, it is getting marked as completed .

**Comment by amansinghbais** [comment]
When we close a item in purchase order then the router redirect us to purchase orders page where all the purchase orders are fetched again using solr query. 

It seems like solr query is taking time to update purchase orders hence the item status not getting updated post closing PO items. Need to find a solution for that.

**Comment by Adameddy26** [comment]
Issue verified and working fine in v2.25.0.
https://jam.dev/c/27dbd808-2764-40c3-a52c-2403b75ccd9f
