### ISSUE TITLE
Auto populate location on added items

### ISSUE THREAD

**Issue by dt2patel** [hotwax/receiving#346]
## Current behavior

If an item is added to a inbound shipment at a facility where it has never been received before, the receiving may be failing.

Need to dry run this and log bug if this is the case.

**Comment by Adameddy26** [comment]
Use case is tested and found that it is working fine.
https://jam.dev/c/05366bfd-2723-476f-bef3-78b521869b57

Took an item for which the shipment is created at a facility but on that facility inventory of this item is 0 or not set(checked in OMS). Then on receiving this item through our app, inventory count is updating successfully in the OMS. Also the shipment card is getting removed from the app after successful receiving of item.

@dt2patel Should I close this?

**Comment by Adameddy26** [comment]
@dt2patel Plz confirm.

**Comment by dt2patel** [comment]
Confirm what? @Adameddy26

**Comment by Adameddy26** [comment]
> Should I close this?

Should I close this ticket as it is working fine?

**Comment by Adameddy26** [comment]
> Confirm what? @Adameddy26

Should I close this ticket as it is working fine?
