### ISSUE TITLE
ShipmentItemSeqId is missing when receiving the externally added item in the shipment

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/receiving#357]
## Current behavior

When adding a new item in the shipment the added item have a shipmentItemSeqId, but on receiving the shipmentItemSeqIId is not passed resulting in error.

## Expected behavior

The newly added item should have a shipmentItemSeqId when receiving the item.

## Steps to reproduce the issue

1. Go to any shipment detail.
2. Add a new item and receive the same item.
3. Check that on receiving the shipmentItemSeqId is not passed in the payload.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in v2.25.0.
https://jam.dev/c/85222db0-a2ee-49d3-a385-e827ae65103d
