### ISSUE TITLE
Barcode Scanning: Concatenating SKU Entries Instead of Overwriting

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/receiving#367]
## Note 
This issue can only be replicated when a physical barcode scanner is used to scan the product.

## Expected behavior
Upon scanning a new product barcode, the scan barcode field should display the SKU of the newly scanned product, overwriting any previously displayed SKU.

## Steps to reproduce the issue
Open the system interface.
Navigate to the section where barcode scanning is utilized.
Scan the barcode of a product (Product A).
Observe that the SKU of Product A is displayed in the scan barcode field.
Scan the barcode of another product (Product B).
Note that instead of replacing the existing SKU, the SKU of Product B is appended to the previous SKU, resulting in an incorrect concatenated SKU.

## Environment details
App version : V2.25.0
App Environment : UAT

**Comment by amansinghbais** [comment]
Here in this issue, we are using a barcode reader as a keyboard input for the ion-input we have created for scanning product SKU. Now the barcode reader works as it takes the value of the barcode as a input in the ion-input and then hit the enter event triggering to scan item. 

The logic currently we have appends the new SKU with the old scanned SKU present in the ion-input. To avoid the following scenario, i have identified following way:--

- We should clear the scanned SKU in the ion-input once succesfully scanning item as we are already showing it in the toast message. And this way whenever user goes to scan an barcode he have a empty ion-input preventing the appending of new SKU with the old SKU.
There is an issue i found in it, that whenever we scan using barcode reader it renders the scanned value in the ion-input and then the enter event is triggered. And the all handling can only be done once the enter event is triggered making the UI to have a flickering effect.
Such that when we scan an item, it displays the SKU for few milliseconds and then clears the ion-input on scanning.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.26.0. Hence, closing it.

**Comment by Adameddy26** [comment]
Changes related to toast message are verified and working fine in release v2.27.0. Hence, closing it.
