### ISSUE TITLE
Product identifiers missing in new product shipment modal.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/receiving#373]
## Expected behavior
Product identifiers should be clearly visible with the product image while adding a new product against any shipment.

## Steps to reproduce the issue
Login the App with valid user credentials.
Go to settings page and select the product identifiers as SHOPIFY_PROD_SKU or ERP_ID or UPCA.
Navigate to shipment or PO page.
Open any shipment.
Choose to add a new shipment.
Search the product which is not part of shipment with its sku.
Observe the issue

## Environment details
App version - v2.26.0
App environment - UAT

## Additional information
![Screenshot from 2024-04-29 17-04-41](https://github.com/hotwax/receiving/assets/158989293/7bb5fd07-a09f-48d7-90a8-314aad386464)

**Comment by ymaheshwari1** [comment]
Add a default identifier if the current selected identifiers are missing. Use the same default identifier as displayed on details page.
Also check this all the other add product modals.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.27.0. Hence, closing it.
https://jam.dev/c/15bef56a-1022-423d-accc-d438ed4ff896
