### ISSUE TITLE
Show Completed Shipments Along with Open Shipments

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/receiving#380]
## What is the motivation for adding/enhancing this feature?
Currently, only open shipments are displayed on the Shipment view and detail page. To enhance user experience and provide a comprehensive view of shipment statuses, we need to display completed shipments along with open shipments.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
Recommended [UI](https://www.figma.com/design/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?node-id=31831-45843&t=pSvfeSW7CzwkswH8-1)

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v2.28.0. Hence, closing this ticket
