### ISSUE TITLE
Item not marked as completed after performing 'Receive and Close' operation during order receipt.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/receiving#386]
## Current behavior
The item is not marked as completed until the page is refreshed or reloaded.

## Expected behavior
Upon performing the 'Receive and Close' operation, the item should be marked as completed without needing to refresh or reload the page.

## Steps to reproduce the issue
Go to the PO section.
Open a PO having multiple items.
Scan any one item of the PO.
Perform the 'Receive and Close' operation.
Observe that the item is not marked as completed.
Refresh/reload the URL.
Check if the item is now marked as completed.

## Environment details
App version : v2.27.0
App environment : UAT

## Additional information
https://jam.dev/c/5eb34534-9f93-470f-93d4-5224c6e3773d

**Comment by amansinghbais** [comment]
When we receive and close an item, we are thrown to the list page of the Purchase orders and there we refetch the order info using Solr. The issue is coming cause Solr is not giving updated order item status.

**Comment by Adameddy26** [comment]
Also it is observed that 'Upon 'Receive and Close' of a PO order containing a single item, the order doesn't get removed from the list page, allowing the user to open and receive the same PO item again.'

**Comment by amansinghbais** [comment]
Will be fixed in this PR: https://github.com/hotwax/receiving/pull/381

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.28.1. Hence, closing this issue.
