### ISSUE TITLE
Call receive shipment item in sync to avoid browser blocking

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/receiving#390]
## What is the motivation for adding/enhancing this feature?

Call receiveShipmentItem in sync instead of async in order to avoid running multiple requests simultaneously causing browser to block.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ravilodhi** [comment]
@Adameddy26 Please update the status of this ticket.

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v2.27.2. Hence, closing this ticket.
