### ISSUE TITLE
Blank header appears on return detail page if ShopifyOrderName and HC OrderID are not present

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/receiving#399]
## Current behavior
The header section appears completely blank, leading to confusion and poor user experience as key return details are missing.

## Expected behavior
When ShopifyOrderName and HC OrderID are missing, the header should display alternative identifiers such as Shipment ID or External ID. If no such identifiers are available, a placeholder message should inform the user that order details are missing, ensuring the header is not blank.

## Steps to reproduce the issue
Navigate to the return section.
Open the detail page of any return.
Ensure that both the ShopifyOrderName and HC OrderID fields are empty or not populated.
Observe the header section of the return detail page.

## Environment details
App version : v2.27.2
App environment : UAT

## Additional information
https://jam.dev/c/67166b53-38c8-4d1f-8938-10dec079b1e0

**Comment by ashutosh7i** [comment]
can i work on this issue?

**Comment by amansinghbais** [comment]
@ashutosh7i , please go ahead

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.27.4. Hence, closing this issue.
