### ISSUE TITLE
Receive shipment enhancement

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/receiving#402]
## What is the motivation for adding/enhancing this feature?
Currently, the receive shipment functionality processes items one by one, making multiple requests equal to the number of items in the shipment. This approach is not scalable. Uploading a JSON of the items to be received and letting the backend logic handle the processing will make it more scalable.

## What are the acceptance criteria?
Shipment items should be uploaded in a single API call and processed on the backend synchronously using the RECEIVE_SHIP_ITEMS data manager configuration. If any item fails, the shipment should not be marked as 'Received,' and the user should still be able to attempt receiving those items. No item should be successfully received more than once.

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ravilodhi** [comment]
This is dependant on OMS release 5.18.0.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.29.0. Hence, closing this issue.
