### ISSUE TITLE
Enable Users to Select Specific Product Identifiers for Barcode Scanning Instead of Limiting to Primary/Secondary

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/receiving#412]
## What is the motivation for adding/enhancing this feature?

Currently, we offer users a choice between primary and secondary product identifiers for barcode scanning. To improve flexibility and user experience, we should enhance this feature by allowing users to directly select the specific identifier they want the barcode scanning to recognize. This change will provide greater control and adaptability, enabling users to tailor the scanning functionality to their specific needs.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.27.5. Hence, closing this ticket.
