### ISSUE TITLE
Show on hand inventory during receiving

### ISSUE THREAD

**Issue by dt2patel** [hotwax/receiving#416]
## What is the motivation for adding/enhancing this feature?

Stores find it helpful to be able to see their on hand inventory while receiving since it helps inform their put away process.

**Comment by dt2patel** [comment]
<img width="1140" alt="Screenshot 2024-11-08 at 12 57 23 PM" src="https://github.com/user-attachments/assets/6a553035-8469-4a86-b568-8bcb37ae1cbd">
We'll show a chip in the middle which replaces the facility location selector. The facility location selection should happen automatically and user no longer has a choice.

Inventory will be lazy loaded and should only load when the user brings the item into view. If the item is not in view, it should not be displayed.

As an enhancement later, maybe we can bring in the on hand inventory at the facility from the same view in the API but for now we can just make an additional API call.

**Comment by Adameddy26** [comment]
Verified the changes and are working fine in release v2.28.1. Hence, closing this issue.
